[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "/about"
identifier = "ErgVc2Oq56"
weight = 3

[[main]]
name = "HyprCrux"
url = "/hyprcrux"
identifier = "xzEwGKbrqy"
weight = 4

[[main]]
name = "Home"
pageRef = "/"
identifier = "U7mJDuEa3c"
weight = 1

[[main]]
name = "Posts"
pageRef = "/posts"
identifier = "4ltrBNtP3i"
weight = 2

[[footer]]
none = "none"
